properties([parameters([choice(choices: ['AWS-Sapient-webserver'])])
pipeline {
    agent any
    stages {
        stage('Preparing') {
            steps {
                sh 'echo Preparing'
            }
        }
        stage('Git Pulling') {
            steps {
                git branch: 'master', url: 'https://github.com/hariharansigamani/Sapient_assesment'
                sh 'ls'
            }
        }
        stage('Init') {
            steps {
                echo "Enter File Name ${params.File_Name}"
                echo "Pipeline Name ${params.Pipeline}"
                withAWS(credentials: 'jenkins-environment', region: 'us-east-1') {
                sh 'terraform -chdir=/var/lib/jenkins/jobs/${Pipeline}/workspace/Non-Modularized/${File_Name}/ init --lock=false'
                }
            }
        }
        stage('Code Analysis') {
            when {
                expression { params.Terraform_Action != 'destroy'}
            }
            steps {
                sh '''
                    sudo curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
                    tfsec Non-Modularized/${File_Name}
                '''
            }
        }
        stage('Action') {
            steps {
                echo "${params.Terraform_Action}"
                withAWS(credentials: 'jenkins-environment', region: 'us-east-1') {
                sh 'terraform get -update' 
                    script {    
                        if (params.Terraform_Action == 'plan') {
                            sh 'terraform -chdir=Non-Modularized/${File_Name}/ plan --lock=false'
                        }   else if (params.Terraform_Action == 'apply') {
                            sh 'terraform -chdir=Non-Modularized/${File_Name}/ apply --lock=false -auto-approve'
                        }   else if (params.Terraform_Action == 'destroy') {
                            sh 'terraform -chdir=Non-Modularized/${File_Name}/ destroy --lock=false -auto-approve'
                        } else {
                            error "Invalid value for Terraform_Action: ${params.Terraform_Action}"
                        }
                    }
                }
                sh 'rm -rf /var/lib/jenkins/jobs/Terraform-Deployment/workspace/env.properties'
            }
        }
    }
}
